name: dart_crypto
description: Helper library for interaction with the Solar network
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  crypto: ^3.0.1 # https://pub.dev/packages/crypto
  hex: ^0.2.0 # https://pub.dev/packages/hex
  base58check: ^2.0.0 # https://pub.dev/packages/base58check

  elliptic: ^0.3.8 # https://pub.dev/packages/elliptic

  pointycastle: ^3.5.2 # https://pub.dev/packages/pointycastle

  schnorr: ^0.0.2 # https://pub.dev/packages/schnorr

  bip340:
    git:
      url: https://github.com/dutchpool/dart-bip340
      ref: master

dev_dependencies:
  lints: ^1.0.0

  test: ^1.21.1
